Target : main.o play.o set.o gos.o save.o cal.o 
	gcc -W -Wall -o  gostop main.o play.o set.o gos.o save.o cal.o
cal.o : cal.c
	gcc -W -Wall -c cal.c
play.o : play.c
	gcc -W -Wall -c play.c
set.o : set.c
	gcc -W -Wall -c set.c
save.o : save.c
	gcc -W -Wall -c save.c
gos.o : gos.c
	gcc -W -Wall -c gos.c

